version: 2

sources:
  - name: staging
    database: seattle-crime-48435
    schema: crime_dataset

    tables:
      - name: seattle_crime_partitioned

models:
  - name: seattle_crime
    description: ""
    columns:
      - name: report_number
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: offense_id
        data_type: int64
        description: ""

      - name: offense_start_datetime
        data_type: datetime
        description: ""

      - name: offense_end_datetime
        data_type: datetime
        description: ""

      - name: report_datetime
        data_type: datetime
        description: ""

      - name: group_a_b
        data_type: string
        description: ""

      - name: crime_against_category
        data_type: string
        description: ""

      - name: offense_parent_group
        data_type: string
        description: ""

      - name: offense
        data_type: string
        description: ""

      - name: offense_code
        data_type: string
        description: ""

      - name: precinct
        data_type: string
        description: ""

      - name: sector
        data_type: string
        description: ""

      - name: beat
        data_type: string
        description: ""

      - name: mcpp
        data_type: string
        description: ""

      - name: block_address
        data_type: string
        description: ""

      - name: longitude
        data_type: float64
        description: ""

      - name: latitude
        data_type: float64
        description: ""

      - name: pseudo_partition_date
        data_type: date
        description: ""
